{
 "title": "Heating - Current",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /.*State/ )\r\n  "
    }
   ]
  },
  {
   "title": "Pumps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /.*Pump.*/ )\r\n  "
    }
   ]
  },
  {
   "title": "Pumps Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /.*Pump.*/ )\r\n  "
    }
   ]
  },
  { "title": "Heating Circuits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Heating Circuit 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC1.*/ )"
    }
   ]
  },
  {
   "title": "Heating Circuit 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC2.*/ )"
    }
   ]
  },
  {
   "title": "HC1 PumpOn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC1.PumpOn/ )"
    }
   ]
  },
  {
   "title": "HC2 PumpOn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC2.PumpOn/ )"
    }
   ]
  },
  { "title": "Buffer & Hot Water", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Buffer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /Buffer.Temp/ )"
    }
   ]
  },
  {
   "title": "Hot Water",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HotWater.*/ )"
    }
   ]
  }
 ]
}