{
 "title": "Heating - History",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /.*State/ )"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /Weather.*Temp/ )"
    }
   ]
  },
  {
   "title": "Heating Circuits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heating Circuit 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC1.*/ )"
    }
   ]
  },
  {
   "title": "Heating Circuit 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HC2.*/ )\r\n "
    }
   ]
  },
  {
   "title": "Buffer & Hot Water",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /Buffer.*/ )"
    }
   ]
  },
  {
   "title": "Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /HotWater.*/ )"
    }
   ]
  },
  {
   "title": "Boiler",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"oekofen\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heating\" and r._field =~ /Boiler.*/ )"
    }
   ]
  }
 ]
}