version: '3'
services:
  influxdb:
    image: arm32v7/influxdb:1.8.10
    ports:
      - 8086:8086
    volumes:
      - "./influxdb-data:/var/lib/influxdb"
      - "./influxdb-config/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    env_file:
      - "./influxdb.env"
  grafana:
    image: grafana/grafana-oss
    ports:
      - 9000:3000
    volumes:
      - "./grafana-data:/var/lib/grafana"
    depends_on:
      - "influxdb"
  collector-app:
    image: wernerfragner/oekofen-collector-app:0.2.2-armv7
    ports:
      - 8080:8080
    volumes:
      - "./collector-app-config/:/config/"
    env_file:
      - "./collector-app.env"
    depends_on:
      - "influxdb"