version: '3'
services:
  influxdb:
    image: arm32v7/influxdb:${INFLUX_DB_VERSION}
    ports:
      - 8086:8086
    volumes:
      - "./influxdb-data:/var/lib/influxdb"
      - "./influxdb-config/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    env_file:
      - "./influxdb.env"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  grafana:
    image: grafana/grafana-oss
    ports:
      - 9000:3000
    volumes:
      - "./grafana-data:/var/lib/grafana"
    depends_on:
      - "influxdb"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  collector-app:
    image: wernerfragner/oekofen-collector-app:${COLLECTOR_APP_VERSION}
    ports:
      - 8080:8080
    volumes:
      - "./collector-app-config/:/config/"
    env_file:
      - "./collector-app.env"
    depends_on:
      - "influxdb"
    logging:
      options:
        max-size: "10m"
        max-file: "3"