version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - "C:/projects/heizung/influxdb:/var/lib/influxdb"
  grafana:
    image: grafana/grafana-oss
    ports:
      - 9000:3000
    volumes:
      - "C:/projects/heizung/grafana:/var/lib/grafana"