version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - "./influxdb-data:/var/lib/influxdb2"
    env_file:
      - "./influxdb.env"
  grafana:
    image: grafana/grafana-oss
    ports:
      - 9000:3000
    volumes:
      - "./grafana-data:/var/lib/grafana"
    depends_on:
      - "influxdb"
  collector-app:
    image: oekofen-collector-app:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    volumes:
      - "./collector-app-config/:/config/"
    env_file:
      - "./collector-app.env"
    depends_on:
      - "influxdb"